import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import Navbar from "@/components/Navbar";
import Loader from "@/components/Loader";
import FluidCursor from "@/components/FluidCursor";
import LenisProvider from "@/components/LenisProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Riya Sisodiya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${inter.variable} cursor-none antialiased`}
      >
        <LenisProvider>
          <Loader />
          <Navbar />
          <FluidCursor />
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
